name: Build and Push Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: fenadmin/telegram_bot:latest
    
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy stack to Portainer
      run: |
        curl -X POST "http://${{ secrets.PORTAINER_URL }}/api/stacks" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.PORTAINER_API_TOKEN }}" \
        --data-binary @docker-compose.yml  # Update with your path

    - name: Update stack in Portainer
      run: |
        curl -X PUT "http://${{ secrets.PORTAINER_URL }}/api/stacks/1" \
        -H "Authorization: Bearer ${{ secrets.PORTAINER_API_TOKEN }}" \
        -H "Content-Type: application/json" \
        --data-binary @docker-compose.yml  # Update with your path
  